### ISSUE TITLE
state.cc infers ViewOfIntegerVariable incorrectly

### ISSUE THREAD

**Issue by mmcilree** [ciaranm/glasgow-constraint-solver#1]
When inferring a Literal involving a view of an integer variable, the order of operations is the wrong way round. 

$-x + c = v$ means $x = -(v - c)$ and not $x = -v - c$.

This affects at least lines 682, 701, 717 (additionally, should this line not have a +1_i as well?) and 849.

**Comment by ciaranm** [comment]
I may or may not have fixed all of the places that this is wrong. We now have some simple unit tests for this, at least.
