### ISSUE TITLE
Nicer API for SmartTable

### ISSUE THREAD

**Issue by ciaranm** [ciaranm/glasgow-constraint-solver#16]
Possibly by making Less etc wrapper classes that convert into constraints or entries.

**Comment by ciaranm** [comment]
I had a play with this, and it's a bit annoying because

- overloading `IntegerVariableID != IntegerVariableID` breaks stuff, so it should be namespaced.
- we would also want `IntegerVariableID == Integer` which clashes with `Literal`
- there's some funky splicing going on in SmartEntry

I think the thing to do is to move the Literal things into a namespace, which will break a lot of code, but give us freedom to muck around more in the future.

**Comment by mmcilree** [comment]
Do we have this now? Worth closing this?

**Comment by ciaranm** [comment]
Yeah, I think it's as good as we'll get for now.
