### ISSUE TITLE
Propagation Algorithms should be decoupled from constraints somehow

### ISSUE THREAD

**Issue by mmcilree** [ciaranm/glasgow-constraint-solver#20]
Maybe we need a separate propagator class or something, but if I want to write a new propagator for Circuit, it seems awkward to have to add a flag use_scc or an enum to choose the propagator. Especially important if we want to experimentally compare different propagation algorithms.

**Comment by ciaranm** [comment]
My first thought is that the best way to do this is to have separate CircuitSCC and CircuitPrevent constraint classes, and to `using Circuit = ` a good default. Perhaps they could share a common base class that does encoding but not propagation.
