### ISSUE TITLE
Encoding of equals literal is incorrect

### ISSUE THREAD

**Issue by mmcilree** [ciaranm/glasgow-constraint-solver#3]
## Issue
When creating a PB variable $x_{=i}$ for some $i$, the generated PB constraints are not correct. Lines [360](https://github.com/ciaranm/glasgow-constraint-solver/blob/8f7c35534f36fd10ab939dfcd26cc42db4379cb7/gcs/innards/proof.cc#L360) and [360](https://github.com/ciaranm/glasgow-constraint-solver/blob/8f7c35534f36fd10ab939dfcd26cc42db4379cb7/gcs/innards/proof.cc#L375) in proof.cc are both >=1, when they should be >= 2. 

## Explanation
As an example, when creating the direct encoding for the literal X=3 (with X having domain {-3,...9}), the following constraints are created. 

$$
\begin{align*}
-32 x_{\text{neg}} + x_{b0} + 2 x_{b1} + 4 x_{b2}  + 8 x_{b3}  + 16 x_{b4} &>= 3 \Leftarrow x_{\geq_3} ; \\
32 x_{\text{neg}} - x_{b0} -2 x_{b1} -4 x_{b2} -8 x_{b3} -16 x_{b4} &>= -2 \Leftarrow \lnot x_{\geq 3} ; \\ \\
-32 x_{\text{neg}} + 1 x_{b0} + 2 x_{b1} + 4 x_{b2} + 8 x_{b3} + 16 x_{b4} &>= 4 \Leftarrow x_{\geq 4} ;\\
32 x_{\text{neg}} - x_{b0} -2 x_{b1} -4 x_{b2} -8 x_{b3} -16 x_{b4} &>= -3 \Leftarrow \lnot x_{\geq 4} ;\\ \\
x_{\geq 4} &>= 1 \Rightarrow x_{\geq 3} ; \\
x_{\geq 3} + \lnot x_{\geq 4} &>= 2 \Leftarrow x_{ = 3} ; \\
x_{\geq 3} + \lnot x_{\geq 4} &>= 1 \Rightarrow x_{ = 3} ; \\
\end{align*}
$$

Consider if the bits representing X were set to 5
$x_{\text{neg}} = 0, x_{b0} = 1, x_{b1} = 0, x_{b2} = 1, x_{b3} = 0, x_{b4} = 0$

The first two constraints would propagate $x_{\geq 3} = 1$
The second two would propagate $x_{\geq 4} = 1$

Then the last constraint would propagate $x_{= 3} = 1$, since $x_{\geq 3}$ + $\lnot x_{\geq 4}$ would be $1 + (1 - 1) >= 1$.

So $x_{=3}$ is true despite X being equal to 5.

**Comment by ciaranm** [comment]
I may or may not have either fixed this or replaced it with something else that is also wrong.
