### ISSUE TITLE
Should we have multiple AllDifferents?

### ISSUE THREAD

**Issue by mmcilree** [ciaranm/glasgow-constraint-solver#30]
Rather than having the propagate_non_gac() just kind of floating in circuit.hh would you be against doing a similar split up as we've done with prevent/scc and have:
```
all_different/all_different.hh
all_different/all_different.cc
all_different/all_different_gac.cc
all_different/all_different_val.cc
```
with an `AllDifferentBase` class that defines the encoding, and then inherited `AllDifferentGAC` and `AllDifferentVal` classes that define the GAC and non-GAC propagators respectively, then finally have a 
 
```
using AllDifferent = AllDifferentGAC
```

so nothing changes on the outside? I think this would make the different versions of circuit cleaner, and also make it easier if something else needs alldiff as a sub-constraint.

**Comment by ciaranm** [comment]
Yes

**Comment by mmcilree** [comment]
Cool. I'll make the changes on the CircuitSCC branch.
