### ISSUE TITLE
Use of VeriPB '==>'

### ISSUE THREAD

**Issue by mmcilree** [ciaranm/glasgow-constraint-solver#4]
We might consider refactoring to remove the use of '==>' and '<==' shorthands entirely, both so that we do reification consistently everywhere, and also because the implementation of this in VeriPB is undocumented and also possibly incorrect.

## Example of why it may be incorrect
model.opb:
```
1 x1 1 x2 >= 1 ==> x3 ;
```
proof.opb:
```
pseudo-Boolean proof version 1.2
f 1 0
```
Then this gives:
```
$ veripb --trace --useColor model.opb proof.opb 
=== begin trace ===
line 002: f 1 0
    ConstraintId 001: 1 ~x1 1 ~x2 1 x3 >= 1
=== end trace ===
```
And if I'm thinking about this correctly, `~x1 + ~x2 + x3 >= 1` is not equivalent to `x1 + x2 >= 1 ==> x3`.
In particular, `x1 = 1; x2 = 0; x=3 = 0` is a solution to the first but not the second.

**Comment by ciaranm** [comment]
I wonder whether it would be worth refactoring so we can write something like

```
    // gevar -> bits
    auto gevar_implies_bits = implied_by(pb_sum(bit_vars) >= v, gevar);
    if (_imp->opb_done) {
        _imp->proof << "red " << gevar_implies_bits << " ; " << gevar << " 0\n";
        ++_imp->proof_line;
    }
    else {
        _imp->opb << gevar_implies_bits << " ;\n";
        ++_imp->model_constraints;
        ++_imp->model_variables;
    }
```
