### ISSUE TITLE
Proof Optimisations

### ISSUE THREAD

**Issue by mmcilree** [ciaranm/glasgow-constraint-solver#45]
Just noting some thoughts while they are in my head

**Even shorter proof names:**
Currently having the proof variable prefixes of the form `i[number] f[number]` is a big saving, but I wonder if we could shorten them even more by having the unique id use the character set `a-zA-Z0-9` i.e. a base 62 encoded number (like https://en.wikipedia.org/wiki/Base62). Obviously won't make a different for small values but once you get into 1000s of extension variables might help a bit. E.g. `f1011e3` would become `fGJe3`, `f13891` would become `f3c3`.

**Deleting ranges**
Just noticing that large chunks of the proofs seem to be deleting consecutive ranges, e.g.

```
line 1126194: del range 718958 718961                                                                      
  ConstraintId  - : deleting 718960, 718958, 718959                                                                         
line 1126195: del range 718962 718965                                                                                       
  ConstraintId  - : deleting 718962, 718963, 718964                                                                         
line 1126196: del range 718966 718969                                                                                       
  ConstraintId  - : deleting 718968, 718966, 718967                                                                         
line 1126197: del range 718970 718973                                                                                       
  ConstraintId  - : deleting 718970, 718971, 718972                                                                         
line 1126198: del range 718974 718978                                                                                       
  ConstraintId  - : deleting 718976, 718977, 718974, 718975                                                                 
line 1126199: del range 718979 718984                                                                                       
  ConstraintId  - : deleting 718979, 718980, 718981, 718982, 718983                                                         
line 1126200: del range 718985 718987                                                                                       
  ConstraintId  - : deleting 718985, 718986                                                                                 
line 1126201: del range 718988 718991                                                                                       
  ConstraintId  - : deleting 718988, 718989, 718990
line 1126202: del range 718992 718994
  ConstraintId  - : deleting 718992, 718993
line 1126203: del range 718995 718997
  ConstraintId  - : deleting 718995, 718996
line 1126204: del range 718998 719001
  ConstraintId  - : deleting 719000, 718998, 718999
line 1126205: del range 719002 719004
  ConstraintId  - : deleting 719002, 7190
```
I don't really understand how this works in the solver but it seems like it would make more sense to collapse these wherever possible. Probably this part needs a rethink anyway as ProofLevels don't entirely work as expected. In particular I found cases where `ProofLevel::Temporary` gets deleted too early - in particular when I have a big state.infer() block with a bunch of temporary p lines in it and then a final rup_under_trail, the p lines get killed before the rup statement is output, which causes the rup to fail. I guess this is linked to #37.

**Comment by ciaranm** [comment]
Can you give me a minimal breaking example for temporary going wrong?

**Comment by ciaranm** [comment]
Ah, that would do it. Probably we want a global "verbosity" setting for proofs, somewhere between "give me small proofs with base62 variable names, and don't waste my time with comments" to "comment all of the things and use long names".
