### ISSUE TITLE
emit_rup_proof_line_under_reason reifying incorrectly?

### ISSUE THREAD

**Issue by mmcilree** [ciaranm/glasgow-constraint-solver#52]
Run into some unexpected failures already for MultBC proofs and I think the culprit is https://github.com/ciaranm/glasgow-constraint-solver/blob/636f4ada2961a50a80ca19363b5a6a2fa9f0582c/gcs/innards/proofs/proof_logger.cc#L402

Should we not have something to deal with negative coefficients in the terms? Otherwise if we try to emit, say

$x - 2y > -1$ under $w \land z$ we're gonna get $-\bar w - \bar z + x - 2y > -1$ rather than $\bar w + \bar z + x - 2y \geq -1$ which is the correct reification representation for $w \land z \implies x - 2y \geq -1$.

Maybe we should be reusing `HalfReifyOnConjunctionOf` to keep the logic for this in one place?

**Comment by ciaranm** [comment]
If you're going to pass negative coefficients to that code, then yes, it should probably be able to deal with negative coefficients. I think there used to be a types-related reason that we had two separate bits of code that worked out how to reify things, but maybe that's no longer a problem. I'll leave this one to you to fix unless you've got too many other things on the go.
